GCP infrastructure using terraform
open-restaurant/restaurant-technology-landscape pull request #2
Opened 2020-11-25 11:31 UTC by MrManning

Adds a basic setup for infrastructure

2020-12-16 16:23 UTC, matthew-green-nandos commented
Hey @MrManning, can pull on the upstream master to incorporate PR that have been merged into master.

2020-12-17 11:57 UTC, MrManning commented
> Hey @MrManning, can pull on the upstream master to incorporate PR that have been merged into master.

Thanks for letting me know, I have just merged master into my fork

2020-12-17 11:58 UTC, MrManning commented
Closed by accident :(

2020-12-17 12:48 UTC, matthew-green-nandos requested changes

2020-12-17 12:48 UTC, matthew-green-nandos commented on infrastructure/gcp/environments/preview/backend.tf
> +
Hey, probably some whitespace that is causing github to say there is no new line.

2020-12-17 12:48 UTC, matthew-green-nandos commented on infrastructure/gcp/environments/preview/main.tf
> +
I think you might be missing the web infrastructure set up.

2020-12-17 12:48 UTC, matthew-green-nandos commented on website/package-lock.json
>  {
please exclude this file from this PR as it seems unrelated to terraform.

2021-01-04 09:48 UTC, matthew-green-nandos approved these changes

2021-01-04 09:49 UTC, merged